/* Import fidèle IRIS Studio : cette feuille ou ce composant conserve le langage éditorial et immersif du dépôt source. */
/**
 * Direction « Portfolio Iris » : les projets deviennent des études de cas aérées, inspirées du rythme de galerie Profilex.
 * La galerie assemble des publications publiques officielles, les dossiers terrain et conserve leur contexte de provenance.
 */
import { ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import LetsPlayProjectLink from "@/components/LetsPlayProjectLink";
import SevenArenaProjectLink from "@/components/SevenArenaProjectLink";
import { partnerProjectBranding } from "@/components/partnerProjectBranding";
import { operationalProjectPath } from "./operationalProjectDetails";
import { operationalProjects } from "./operationalProjectsContent";
import "./Operations.css";

export default function Projects() {
  return <div className="page-shell"><SiteHeader /><main>
    <section className="portfolio-page-intro section-pad" aria-labelledby="projects-title"><div className="portfolio-eye" aria-hidden="true"><i /><i /><i /></div><div><p className="eyebrow">Portfolio Iris Studio</p><h1 id="projects-title">Des projets avec une<br /><em>vie propre.</em></h1></div><p>Des formats culturels, communautaires et opérationnels accompagnés de l’intention à la présence concrète.</p></section>
    <section className="portfolio-directory section-pad"><p>Études de cas sélectionnées <span>02</span></p><div><LetsPlayProjectLink><span>01</span><strong>Let’s Play</strong><em>Gaming & pop culture</em><ArrowUpRight size={24} /></LetsPlayProjectLink><SevenArenaProjectLink><span>02</span><strong>7ouma Arena</strong><em>E-sport & communauté</em><ArrowUpRight size={24} /></SevenArenaProjectLink></div></section>
    <section className="projects-cards section-pad"><LetsPlayProjectLink className="project-case case-letsplay"><div className="project-case-media project-case-media-brand project-case-media-letsplay project-case-media-thumbnail"><img src={partnerProjectBranding.letsPlay.thumbnail} alt={partnerProjectBranding.letsPlay.thumbnailAlt} /><span>01</span></div><div className="project-case-copy"><p>Let’s Play × Algérie Télécom</p><h2>La pop culture<br /><em>sur le terrain.</em></h2><span>Découvrir le projet <ArrowUpRight size={18} /></span></div></LetsPlayProjectLink><SevenArenaProjectLink className="project-case case-arena"><div className="project-case-media project-case-media-brand project-case-media-arena project-case-media-thumbnail"><img src={partnerProjectBranding.sevenArena.thumbnail} alt={partnerProjectBranding.sevenArena.thumbnailAlt} /><span>02</span></div><div className="project-case-copy"><p>7ouma Arena × Djezzy</p><h2>L’arène est<br /><em>dans la 7ouma.</em></h2><span>Découvrir le projet <ArrowUpRight size={18} /></span></div></SevenArenaProjectLink></section>
    <section className="operations-ledger section-pad" aria-labelledby="operations-title"><div className="iris-route-line iris-route-line-operations" aria-hidden="true"><i /><i /><i /></div><div className="operations-ledger-heading"><div><p className="eyebrow">Dossiers opérationnels</p><h2 id="operations-title" className="display-title">L’idée se mesure<br />quand elle <em>agit.</em></h2></div><p>Des projets de merchandising, de déploiement et de dispositif de marque, illustrés par les archives LinkedIn Iris Studio fournies par l’équipe.</p></div><div className="operations-project-grid">{operationalProjects.map((project) => <Link key={project.id} href={operationalProjectPath(project.id)} className="operation-record-link"><article className={`operation-record ${project.wide ? "operation-record-wide" : ""}`}><figure className="operation-record-media"><img src={project.image} alt={project.alt} /><figcaption>{project.sourceLabel}</figcaption></figure><div className="operation-record-content"><div className="operation-record-top"><span className="operation-record-index">{project.index}</span><span className="operation-record-tag">{project.tag}</span></div><h3>{project.title} <em>{project.accent}</em></h3><p>{project.text}</p></div></article></Link>)}</div><p className="operations-ledger-source">Dossiers issus d’archives LinkedIn Iris Studio fournies par l’équipe. <span>Mission, période et visuels reproduits selon les publications.</span></p></section>
    <section className="social-gallery section-pad" aria-labelledby="gallery-title"><div className="gallery-heading"><div><p className="eyebrow">Galerie de terrain</p><h2 id="gallery-title" className="display-title">Les communautés,<br /><em>en images réelles.</em></h2></div><p>Une sélection de publications issues des chaînes YouTube officielles de Let’s Play et 7ouma Arena. Chaque image renvoie vers sa publication d’origine.</p></div><div className="social-gallery-grid"><a className="gallery-item gallery-item-wide" href="https://www.youtube.com/watch?v=HzigJZOxz2o" target="_blank" rel="noreferrer"><img src="assets/letsplay-comiccon_56bebf05.jpg" alt="Games and Comic Con Dzair, publication Let’s Play" /><span>Let’s Play <i>Games & Comic Con Dzair</i></span></a><a className="gallery-item" href="https://www.youtube.com/watch?v=0ThNyFItASM" target="_blank" rel="noreferrer"><img src="assets/letsplay-awards_5ae8bad7.jpg" alt="Let’s Play Awards 2025" /><span>Let’s Play <i>Awards 2025</i></span></a><a className="gallery-item" href="https://www.youtube.com/watch?v=Zl6crcrPnPQ" target="_blank" rel="noreferrer"><img src="assets/letsplay-asus_c5260be3.jpg" alt="Inside ASUS Experts Day 2025" /><span>Let’s Play <i>ASUS Experts Day</i></span></a><a className="gallery-item" href="https://www.youtube.com/watch?v=tSfGgsWUQZc" target="_blank" rel="noreferrer"><img src="assets/7ouma-bestof_6027ec99.jpg" alt="The Best of 7ouma Arena by Djezzy" /><span>7ouma Arena <i>The Best Of</i></span></a><a className="gallery-item" href="https://www.youtube.com/watch?v=Gw_MYGNP3V8" target="_blank" rel="noreferrer"><img src="assets/7ouma-indie-games_3c1c437a.jpg" alt="Indie Games, 7ouma Arena" /><span>7ouma Arena <i>Indie Games</i></span></a><a className="gallery-item gallery-item-wide" href="https://www.youtube.com/watch?v=1i3jSTIVv0w" target="_blank" rel="noreferrer"><img src="assets/7ouma-free-fire_695c5d6f.jpg" alt="Free Fire Hangout, 7ouma Arena" /><span>7ouma Arena <i>Free Fire Hangout</i></span></a></div><p className="gallery-source">Sources publiques : chaînes YouTube officielles Let’s Play et 7ouma Arena. <span>Cliquer sur une image pour consulter la publication.</span></p></section>
    <section className="page-next section-pad"><p>Prochaine étape / 04</p><Link href="/contact"><span>Donner une scène<br /><em>à votre projet.</em></span><ArrowUpRight size={34} /></Link></section>
  </main><SiteFooter /></div>;
}
